### ISSUE TITLE
不能解析 <wxs src="xxx" /> 之类的自闭和标签

### ISSUE THREAD

**Issue by NiuZhuang** [LeeJim/wxml-parser#4]
在test case 中加上如下标签，case 会不通过：
```xml
<include src="../myAll.wxml"/>
<wxs src="../picFilter.wxs" module="picFilter"/>
```
结果：
```
    - <include src="../myAll.wxml"/>
    + <include src="../myAll.wxml">
```

**Comment by wanghaooo** [comment]
> 在test case 中加上如下标签，case 会不通过：
> 
> ```
> <include src="../myAll.wxml"/>
> <wxs src="../picFilter.wxs" module="picFilter"/>
> ```
> 
> 结果：
> 
> ```
>     - <include src="../myAll.wxml"/>
>     + <include src="../myAll.wxml">
> ```

我也遇到这个问题了，请问你后面解决了吗

**Comment by NiuZhuang** [comment]
> > 在test case 中加上如下标签，case 会不通过：
> > ```
> > <include src="../myAll.wxml"/>
> > <wxs src="../picFilter.wxs" module="picFilter"/>
> > ```
> > 
> > 
> > 结果：
> > ```
> >     - <include src="../myAll.wxml"/>
> >     + <include src="../myAll.wxml">
> > ```
> 
> 我也遇到这个问题了，请问你后面解决了吗

没有，我后来用 [htmlparser2](https://github.com/fb55/htmlparser2) 做了

**Comment by wanghaooo** [comment]
> > > 在test case 中加上如下标签，case 会不通过：
> > > ```
> > > <include src="../myAll.wxml"/>
> > > <wxs src="../picFilter.wxs" module="picFilter"/>
> > > ```
> > > 
> > > 
> > > 结果：
> > > ```
> > >     - <include src="../myAll.wxml"/>
> > >     + <include src="../myAll.wxml">
> > > ```
> > 
> > 
> > 我也遇到这个问题了，请问你后面解决了吗
> 
> 没有，我后来用 [htmlparser2](https://github.com/fb55/htmlparser2) 做了

好的，感谢

**Comment by dhlolo** [comment]
这个包不是还是miniprogram-ci里依赖的么

> > > 在test case 中加上如下标签，case 会不通过：
> > > ```
> > > <include src="../myAll.wxml"/>
> > > <wxs src="../picFilter.wxs" module="picFilter"/>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 结果：
> > > ```
> > >     - <include src="../myAll.wxml"/>
> > >     + <include src="../myAll.wxml">
> > > ```
> > 
> > 
> > 我也遇到这个问题了，请问你后面解决了吗
> 
> 没有，我后来用 [htmlparser2](https://github.com/fb55/htmlparser2) 做了

用htmlparser2做，也需要对{{}}的部分做特殊的处理，因为其中可能有{{ ..>.. }}解析为标签的情况，我是先用把{{}}部分替换成静态，然后单独处理，有可以直接将表达式内容融入htmlparser2的ast的方式么？

**Comment by NiuZhuang** [comment]
> 

有个库 https://github.com/jneen/parsimmon 可以自己设定一个语言的关键词，例如把 {{ 和 }} 设置为关键词，然后生成 ast

具体的用法，需要你研究下.

**Comment by dhlolo** [comment]
> > 
> 
> 有个库 https://github.com/jneen/parsimmon 可以自己设定一个语言的关键词，例如把 {{ 和 }} 设置为关键词，然后生成 ast
> 
> 具体的用法，需要你研究下.

感谢。看了下，似乎除了对{{和}}之外，还需要自己把htmlparser2的主逻辑也自己实现下么？其实目前htmlparser2可以解决大部分问题，我给他们也提了PR，不过像wxml语法还是在w3c标准之外的，正在考虑要不要fork一份加上wxml的逻辑。因为如果用这个parsimmon还要自己实现xml解析逻辑的话，感觉还是比较复杂。

**Comment by NiuZhuang** [comment]
是的， parsimmon 是抛开 htmlparser2 那一套了，重新实现

**Comment by NiuZhuang** [comment]
> 
我看实现起来也并不复杂，他们给了一个 xml 的例子，wxml 无非是改一改就可以了
https://github.com/jneen/parsimmon/blob/master/examples/xml-ish.js

**Comment by LeeJim** [comment]
已修复，对应 commit：
822d7e056cc1896e307e517f51d54f6b8f6d013e

**Comment by LeeJim** [comment]
已发布 v0.1.2

**Comment by dhlolo** [comment]
> > 
> 
> 我看实现起来也并不复杂，他们给了一个 xml 的例子，wxml 无非是改一改就可以了 https://github.com/jneen/parsimmon/blob/master/examples/xml-ish.js

感谢~
